name: Lint project

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"
      
      - name: Install Yarn
        run: npm install --global yarn@1.22.15
      
      - name: Install dependencies
        run: yarn install
        
      - name: Lint source files
        run: yarn run lint
